/* eslint-disable no-unused-vars */
export enum ReportType {
    fund = 'fundInternal',
    funds = 'fundsList',
    fundAvailability = 'fundAvailability',
    fundsListInternal = 'fundsListInternal',
    fundMemoriesListInternalReport = 'fundMemoriesListInternalReport',
    fundMemoriesList = 'fundMemoriesList',
    partialReceiptsList = 'partialReceiptsList',
    receiptsList = 'receiptsList',
    workListForPriorityRestoration = 'workListForPriorityRestoration',
    inventoryBook = 'inventoryBook',
    inventoryBookOfCopiesFromForeignArchives = 'inventoryBookOfCopiesFromForeignArchives',
    compilationAndNTOOfEDocuments = 'compilationAndNTOOfEDocuments',
    insuranceFundOfCopiesOfForeignArchives = 'insuranceFundOfCopiesOfForeignArchives',
    registerOfDigitizedDocumentsReport = 'registerOfDigitizedDocumentsReport',
    countOfUsedCopiesOfDocumentsFromForeignArchivesReport = 'countOfUsedCopiesOfDocumentsFromForeignArchivesReport',
    qualityControlReport = 'qualityControlReport',
    specialRegistrationListReport = 'specialRegistrationListReport',
    numberOfArchiveEntitiesOrderedByReaderReport = 'numberOfArchiveEntitiesOrderedByReaderReport',
    numberOfArchiveEntitiesOrderedByEmployeeReport = 'numberOfArchiveEntitiesOrderedByEmployeeReport',
    mostUsedRequestEntitiesReport = 'mostUsedRequestEntitiesReport',
    numberOfDocumentsOrderedByReaderReport = 'numberOfDocumentsOrderedByReaderReport',
    numberOfDocumentsOrderedByEmployeeReport = 'numberOfDocumentsOrderedByEmployeeReport',
    activeProcessesReport = 'activeProcessesReport',
    inventoryReport = 'inventoryReport',
    listOfRoughDocumentsReport = 'listOfRoughDocumentsReport',
    digitalDocumentsUsageReport = 'digitalDocumentsUsageReport',
    listOfPartialReceiptsInArchiveReport = 'listOfPartialReceiptsInArchiveReport',
    userActionsJournalReport = 'userActionsJournalReport',
    cardForm1InternalData = 'cardForm1InternalData',
    cardForm1Data = 'CardForm1Data',
    fundData = 'fundDataInternal',
    workDoneOnDigitalObjectsReport = 'workDoneOnDigitalObjectsReport',
    accountAndDescriptionOfFilmDocumentsBook = 'accountAndDescriptionOfFilmDocumentsBook',
    digitalObjectsPreparationReport = "digitalObjectsPreparationReport"
}
export enum ReportResultType {
    BothDBs = 1,
    ExternalDB = 2,
    InternalDB = 3,
}
