
export enum RoleNames {
    GroupA = "Служител от група А (A)",
    GroupB = "Служител от група Б (B)",
    GroupB1 = "Служител от група Б1 (B1)",
    GroupV1 = "Служител от група В1 (V1)",
    GroupV2 = "Служител от група В2 (V2)",
    GroupV3 = "Служител от група В3 (V3)",
    GroupV4 = "Служител от група В4 (V4)",
    GroupV5 = "Служител от група В5 (V5)",
    GroupV6 = "Служител от група В6 (V6)",
    GroupG = "Служител от група Г (G)",
    GroupG1 = "Служител от група Г1 (G1)",
    GroupG2 = "Служител от група Г2 (G2)",
    GroupD1 = "Служител от група Д1 (D1)",
    GroupD2 = "Служител от група Д2 (D2)",
    GroupD3 = "Служител от група Д3 (D3)",
    GroupE = "Служител от група Е (E)",
    GroupJ = "Служител от група Ж (J)",
    GroupZ = "Служител от група З (Z)",
    GroupI = "Служител от група И (I)",
    GroupI1 = "Служител от група И1 (I1)",
}


export enum RoleAbbreviations {
    GroupA = "A",
    GroupB = "B",
    GroupB1 = "B1",
    GroupV1 = "V1",
    GroupV2 = "V2",
    GroupV3 = "V3",
    GroupV4 = "V4",
    GroupV5 = "V5",
    GroupV6 = "V6",
    GroupG = "G",
    GroupG1 = "G1",
    GroupG2 = "G2",
    GroupD1 = "D1",
    GroupD2 = "D2",
    GroupD3 = "D3",
    GroupE = "E",
    GroupJ = "J",
    GroupZ = "Z",
    GroupI = "I",
    GroupI1 = "I1",
}
