using System;
using System.Collections.Generic;

namespace DAA.Data
{
    public partial class FileUploadQueue
    {
        public int Id { get; set; }
        public Guid CreatedGuid { get; set; }
        public Guid? FinishedGuid { get; set; }
        public Guid UserId { get; set; }
        public string ComputerName { get; set; } = null!;
        public string LocalFileName { get; set; } = null!;
        public string Checksum { get; set; } = null!;
        public string FileName { get; set; } = null!;
        public string ProcessKindCode { get; set; } = null!;
        public string? FileKindCode { get; set; }
        public Guid DocumentId { get; set; }
        public bool? AutoGenerateDerivative { get; set; }
        public Guid? MasterDocumentId { get; set; }
        public string? Notes { get; set; }
        public long Size { get; set; }
        public long Position { get; set; }
        public bool Finished { get; set; }
        public string DbFileName { get; set; } = null!;
        public string? UncFileName { get; set; }
        public bool? ChecksumCheckResult { get; set; }
        public bool? FileFormatCheckResult { get; set; }
        public bool? AntivirusCheckResult { get; set; }
        public string? AntivirusCheckInfo { get; set; }
        public string? FileInfo { get; set; }
        public string? ErrorMessage { get; set; }
    }
}
