export interface IFundReconstructionModel
{
    id?: number,
    processId?: number,
    archiveId?: number,
    fundSystemIdentifier?: string,
    sourceInventorySystemIdentifier?: string,
    sourceInventoryNumber?: string,
    sourceArchivalEntitySystemIdentifier?: string,
    sourceArchivalEntityNumber?: string,
    sourceDocumentSystemIdentifier?: string,
    sourceDocumentTitle?: string,
    targetInventorySystemIdentifier?: string,
    targetInventoryNumber?: string,
    targetArchivalEntitySystemIdentifier?: string,
    targetArchivalEntityNumber?: string,
    targetDocumentSystemIdentifier?: string,
    targetDocumentTitle?: string,
    availabilityStatusCode?: number,
    availabilityStatusText?: string,
    createdOn?: Date,
    deletedOn?: Date,
    updatedOn?: Date,
    createdBy?: string,
    deletedBy?: string,
    updatedBy?: string;
    deleted?: boolean,
    createdByUserName?: string,
    createdByDisplayName?: string,
    updatedByUserName?: string,
    updatedByDisplayName?: string,
    deletedByUserName?: string,
    deletedByDisplayName?: string,
}