using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAA.Models.FileUploadApp
{
    public class QueueItemBaseModel
    {
        public string? ComputerName { get; set; }
        public bool Finished { get; set; }
    }

    public class QueueItemModel : QueueItemBaseModel
    {
        public int Id { get; set; }
        public Guid CreatedGuid { get; set; }
        public Guid? FinishedGuid { get; set; }

        public int Sort1 { get; set; }
        public int Sort2 { get; set; }

        public string LocalFileName { get; set; } = null!;
        public string Checksum { get; set; } = null!;

        public ProcessKind ProcessKind { get; set; }
        public FileKind? FileKind { get; set; }
        public Guid DocumentId { get; set; }
        public bool? AutoGenerateDerivative { get; set; }
        public Guid? MasterDocumentId { get; set; }
        public string? Notes { get; set; }
        public long Size { get; set; }
        public long Position { get; set; }

        public string? DbFileName { get; set; }

        public bool? ChecksumCheckResult { get; set; }
        public bool? FileFormatCheckResult { get; set; }
        public bool? AntivirusCheckResult { get; set; }
        public string? AntivirusCheckInfo { get; set; }

        public string? FileInfo { get; set; }
        public string? ErrorMessage { get; set; }

        public QueueItemModel Clone()
        {
            return (QueueItemModel)MemberwiseClone();
        }

        [JsonIgnore]
        public JobStatus JobStatus { get; set; }
    }
}
