<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Document\**" />
    <EmbeddedResource Remove="Document\**" />
    <None Remove="Document\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Models\ArchiveEntityOfListRequestModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.31" />
    <PackageReference Include="Hangfire.Core" Version="1.7.31" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.7.31" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="6.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.9" />
    <PackageReference Include="Serilog.AspNetCore" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DAA.Data.Files\DAA.Data.Files.csproj" />
    <ProjectReference Include="..\DAA.Data\DAA.Data.csproj" />
    <ProjectReference Include="..\DAA.Models\DAA.Models.csproj" />
    <ProjectReference Include="..\DAA.Shared\DAA.Shared.csproj" />
  </ItemGroup>

</Project>
