namespace DAA.App.FileUpload
{
    partial class FileEditForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            browseButton = new Button();
            fileKindMasterRadioButton = new RadioButton();
            fileKindDerivativeRadioButton = new RadioButton();
            fileKindDemoRadioButton = new RadioButton();
            processKindKmfRadioButton = new RadioButton();
            processKindFundRadioButton = new RadioButton();
            fileKindGroupBox = new GroupBox();
            processKindGroupBox = new GroupBox();
            processKindRawRadioButton = new RadioButton();
            processKindEdRadioButton = new RadioButton();
            openFileDialog = new OpenFileDialog();
            cancelButton = new Button();
            okButton = new Button();
            errorProvider = new ErrorProvider(components);
            documentIdLabel = new Label();
            documentIdTextBox = new TextBox();
            label3 = new Label();
            masterFileNameComboBox = new ComboBox();
            label4 = new Label();
            masterFileIdPanel = new Panel();
            autoGenerateDerivativeCheckBox = new CheckBox();
            label1 = new Label();
            notesTextBox = new TextBox();
            fileInfoButton = new Button();
            mainPanel = new Panel();
            fileNamesListBox = new ListBox();
            infoPanel = new Panel();
            infoTabControl = new TabControl();
            infoTabPage = new TabPage();
            infoTextBox = new TextBox();
            info2TabPage = new TabPage();
            info2TextBox = new TextBox();
            pictureBox = new PictureBox();
            fileNameTextBox = new TextBox();
            fileKindGroupBox.SuspendLayout();
            processKindGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)errorProvider).BeginInit();
            masterFileIdPanel.SuspendLayout();
            mainPanel.SuspendLayout();
            infoPanel.SuspendLayout();
            infoTabControl.SuspendLayout();
            infoTabPage.SuspendLayout();
            info2TabPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox).BeginInit();
            SuspendLayout();
            // 
            // browseButton
            // 
            browseButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            browseButton.Location = new Point(842, 158);
            browseButton.Name = "browseButton";
            browseButton.Size = new Size(88, 25);
            browseButton.TabIndex = 11;
            browseButton.Text = "Избор";
            browseButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            browseButton.UseVisualStyleBackColor = true;
            browseButton.Click += BrowseButton_Click;
            // 
            // fileKindMasterRadioButton
            // 
            fileKindMasterRadioButton.AutoSize = true;
            fileKindMasterRadioButton.Location = new Point(16, 22);
            fileKindMasterRadioButton.Name = "fileKindMasterRadioButton";
            fileKindMasterRadioButton.Size = new Size(73, 19);
            fileKindMasterRadioButton.TabIndex = 4;
            fileKindMasterRadioButton.TabStop = true;
            fileKindMasterRadioButton.Text = "Основен";
            fileKindMasterRadioButton.UseVisualStyleBackColor = true;
            fileKindMasterRadioButton.CheckedChanged += FileKind_Changed;
            // 
            // fileKindDerivativeRadioButton
            // 
            fileKindDerivativeRadioButton.AutoSize = true;
            fileKindDerivativeRadioButton.Location = new Point(16, 44);
            fileKindDerivativeRadioButton.Name = "fileKindDerivativeRadioButton";
            fileKindDerivativeRadioButton.Size = new Size(69, 19);
            fileKindDerivativeRadioButton.TabIndex = 5;
            fileKindDerivativeRadioButton.TabStop = true;
            fileKindDerivativeRadioButton.Text = "Произв.";
            fileKindDerivativeRadioButton.UseVisualStyleBackColor = true;
            fileKindDerivativeRadioButton.CheckedChanged += FileKind_Changed;
            // 
            // fileKindDemoRadioButton
            // 
            fileKindDemoRadioButton.AutoSize = true;
            fileKindDemoRadioButton.Location = new Point(16, 66);
            fileKindDemoRadioButton.Name = "fileKindDemoRadioButton";
            fileKindDemoRadioButton.Size = new Size(55, 19);
            fileKindDemoRadioButton.TabIndex = 6;
            fileKindDemoRadioButton.TabStop = true;
            fileKindDemoRadioButton.Text = "Демо";
            fileKindDemoRadioButton.UseVisualStyleBackColor = true;
            fileKindDemoRadioButton.CheckedChanged += FileKind_Changed;
            // 
            // processKindKmfRadioButton
            // 
            processKindKmfRadioButton.AutoSize = true;
            processKindKmfRadioButton.Checked = true;
            processKindKmfRadioButton.Location = new Point(16, 63);
            processKindKmfRadioButton.Name = "processKindKmfRadioButton";
            processKindKmfRadioButton.Size = new Size(52, 19);
            processKindKmfRadioButton.TabIndex = 1;
            processKindKmfRadioButton.TabStop = true;
            processKindKmfRadioButton.Text = "КМФ";
            processKindKmfRadioButton.UseVisualStyleBackColor = true;
            processKindKmfRadioButton.CheckedChanged += ProcessKind_Changed;
            // 
            // processKindFundRadioButton
            // 
            processKindFundRadioButton.AutoSize = true;
            processKindFundRadioButton.Location = new Point(16, 41);
            processKindFundRadioButton.Name = "processKindFundRadioButton";
            processKindFundRadioButton.Size = new Size(54, 19);
            processKindFundRadioButton.TabIndex = 2;
            processKindFundRadioButton.Text = "Фонд";
            processKindFundRadioButton.UseVisualStyleBackColor = true;
            processKindFundRadioButton.CheckedChanged += ProcessKind_Changed;
            // 
            // fileKindGroupBox
            // 
            fileKindGroupBox.Controls.Add(fileKindMasterRadioButton);
            fileKindGroupBox.Controls.Add(fileKindDerivativeRadioButton);
            fileKindGroupBox.Controls.Add(fileKindDemoRadioButton);
            fileKindGroupBox.Location = new Point(142, 12);
            fileKindGroupBox.Name = "fileKindGroupBox";
            fileKindGroupBox.Size = new Size(100, 111);
            fileKindGroupBox.TabIndex = 3;
            fileKindGroupBox.TabStop = false;
            fileKindGroupBox.Text = "Вид файл";
            fileKindGroupBox.Visible = false;
            // 
            // processKindGroupBox
            // 
            processKindGroupBox.Controls.Add(processKindRawRadioButton);
            processKindGroupBox.Controls.Add(processKindEdRadioButton);
            processKindGroupBox.Controls.Add(processKindKmfRadioButton);
            processKindGroupBox.Controls.Add(processKindFundRadioButton);
            processKindGroupBox.Location = new Point(12, 12);
            processKindGroupBox.Name = "processKindGroupBox";
            processKindGroupBox.Size = new Size(109, 111);
            processKindGroupBox.TabIndex = 0;
            processKindGroupBox.TabStop = false;
            processKindGroupBox.Text = "Процес";
            // 
            // processKindRawRadioButton
            // 
            processKindRawRadioButton.AutoSize = true;
            processKindRawRadioButton.Location = new Point(16, 85);
            processKindRawRadioButton.Name = "processKindRawRadioButton";
            processKindRawRadioButton.Size = new Size(81, 19);
            processKindRawRadioButton.TabIndex = 4;
            processKindRawRadioButton.Text = "Груб опис";
            processKindRawRadioButton.UseVisualStyleBackColor = true;
            processKindRawRadioButton.CheckedChanged += ProcessKind_Changed;
            // 
            // processKindEdRadioButton
            // 
            processKindEdRadioButton.AutoSize = true;
            processKindEdRadioButton.Location = new Point(16, 19);
            processKindEdRadioButton.Name = "processKindEdRadioButton";
            processKindEdRadioButton.Size = new Size(39, 19);
            processKindEdRadioButton.TabIndex = 3;
            processKindEdRadioButton.Text = "ЕД";
            processKindEdRadioButton.UseVisualStyleBackColor = true;
            // 
            // cancelButton
            // 
            cancelButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            cancelButton.CausesValidation = false;
            cancelButton.DialogResult = DialogResult.Cancel;
            cancelButton.Location = new Point(842, 237);
            cancelButton.Name = "cancelButton";
            cancelButton.Size = new Size(88, 25);
            cancelButton.TabIndex = 14;
            cancelButton.Text = "Отмяна";
            cancelButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            cancelButton.UseVisualStyleBackColor = true;
            // 
            // okButton
            // 
            okButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            okButton.Location = new Point(748, 237);
            okButton.Name = "okButton";
            okButton.Size = new Size(88, 25);
            okButton.TabIndex = 13;
            okButton.Text = "Запис";
            okButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            okButton.UseVisualStyleBackColor = true;
            okButton.Click += okButton_Click;
            // 
            // errorProvider
            // 
            errorProvider.ContainerControl = this;
            // 
            // documentIdLabel
            // 
            documentIdLabel.AutoSize = true;
            documentIdLabel.Location = new Point(273, 15);
            documentIdLabel.Name = "documentIdLabel";
            documentIdLabel.Size = new Size(61, 15);
            documentIdLabel.TabIndex = 14;
            documentIdLabel.Text = "Документ";
            // 
            // documentIdTextBox
            // 
            documentIdTextBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            documentIdTextBox.Location = new Point(381, 12);
            documentIdTextBox.Name = "documentIdTextBox";
            documentIdTextBox.Size = new Size(549, 23);
            documentIdTextBox.TabIndex = 7;
            documentIdTextBox.Enter += documentIdTextBox_Enter;
            documentIdTextBox.Leave += documentIdTextBox_Leave;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Location = new Point(0, 3);
            label3.Name = "label3";
            label3.Size = new Size(90, 15);
            label3.TabIndex = 16;
            label3.Text = "Основен файл:";
            // 
            // masterFileNameComboBox
            // 
            masterFileNameComboBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            masterFileNameComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            masterFileNameComboBox.FormattingEnabled = true;
            masterFileNameComboBox.Location = new Point(108, 0);
            masterFileNameComboBox.Name = "masterFileNameComboBox";
            masterFileNameComboBox.Size = new Size(313, 23);
            masterFileNameComboBox.TabIndex = 8;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Location = new Point(12, 158);
            label4.Name = "label4";
            label4.Size = new Size(36, 15);
            label4.TabIndex = 18;
            label4.Text = "Файл";
            // 
            // masterFileIdPanel
            // 
            masterFileIdPanel.Controls.Add(label3);
            masterFileIdPanel.Controls.Add(masterFileNameComboBox);
            masterFileIdPanel.Location = new Point(273, 41);
            masterFileIdPanel.Name = "masterFileIdPanel";
            masterFileIdPanel.Size = new Size(421, 23);
            masterFileIdPanel.TabIndex = 19;
            masterFileIdPanel.Visible = false;
            // 
            // autoGenerateDerivativeCheckBox
            // 
            autoGenerateDerivativeCheckBox.AutoSize = true;
            autoGenerateDerivativeCheckBox.Location = new Point(777, 43);
            autoGenerateDerivativeCheckBox.Name = "autoGenerateDerivativeCheckBox";
            autoGenerateDerivativeCheckBox.Size = new Size(153, 19);
            autoGenerateDerivativeCheckBox.TabIndex = 15;
            autoGenerateDerivativeCheckBox.Text = "Генерирай производен";
            autoGenerateDerivativeCheckBox.UseVisualStyleBackColor = true;
            autoGenerateDerivativeCheckBox.Visible = false;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Location = new Point(273, 67);
            label1.Name = "label1";
            label1.Size = new Size(55, 15);
            label1.TabIndex = 15;
            label1.Text = "Бележки";
            // 
            // notesTextBox
            // 
            notesTextBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            notesTextBox.Location = new Point(273, 85);
            notesTextBox.Multiline = true;
            notesTextBox.Name = "notesTextBox";
            notesTextBox.Size = new Size(657, 64);
            notesTextBox.TabIndex = 9;
            // 
            // fileInfoButton
            // 
            fileInfoButton.Location = new Point(12, 208);
            fileInfoButton.Name = "fileInfoButton";
            fileInfoButton.Size = new Size(75, 25);
            fileInfoButton.TabIndex = 12;
            fileInfoButton.Text = "Info";
            fileInfoButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            fileInfoButton.UseVisualStyleBackColor = true;
            fileInfoButton.Click += fileInfoButton_Click;
            // 
            // mainPanel
            // 
            mainPanel.Controls.Add(fileNamesListBox);
            mainPanel.Controls.Add(autoGenerateDerivativeCheckBox);
            mainPanel.Controls.Add(okButton);
            mainPanel.Controls.Add(cancelButton);
            mainPanel.Controls.Add(browseButton);
            mainPanel.Dock = DockStyle.Top;
            mainPanel.Location = new Point(0, 0);
            mainPanel.Name = "mainPanel";
            mainPanel.Size = new Size(963, 271);
            mainPanel.TabIndex = 21;
            // 
            // fileNamesListBox
            // 
            fileNamesListBox.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point);
            fileNamesListBox.FormattingEnabled = true;
            fileNamesListBox.ItemHeight = 17;
            fileNamesListBox.Location = new Point(93, 156);
            fileNamesListBox.Name = "fileNamesListBox";
            fileNamesListBox.ScrollAlwaysVisible = true;
            fileNamesListBox.Size = new Size(743, 72);
            fileNamesListBox.TabIndex = 16;
            fileNamesListBox.SelectedIndexChanged += fileNamesListBox_SelectedIndexChanged;
            // 
            // infoPanel
            // 
            infoPanel.Controls.Add(infoTabControl);
            infoPanel.Controls.Add(pictureBox);
            infoPanel.Dock = DockStyle.Fill;
            infoPanel.Location = new Point(0, 271);
            infoPanel.Name = "infoPanel";
            infoPanel.Size = new Size(963, 451);
            infoPanel.TabIndex = 22;
            // 
            // infoTabControl
            // 
            infoTabControl.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            infoTabControl.Controls.Add(infoTabPage);
            infoTabControl.Controls.Add(info2TabPage);
            infoTabControl.Location = new Point(3, 0);
            infoTabControl.Name = "infoTabControl";
            infoTabControl.SelectedIndex = 0;
            infoTabControl.Size = new Size(308, 448);
            infoTabControl.TabIndex = 10;
            // 
            // infoTabPage
            // 
            infoTabPage.Controls.Add(infoTextBox);
            infoTabPage.Location = new Point(4, 24);
            infoTabPage.Name = "infoTabPage";
            infoTabPage.Padding = new Padding(3);
            infoTabPage.Size = new Size(300, 420);
            infoTabPage.TabIndex = 0;
            infoTabPage.Text = "Info ";
            infoTabPage.UseVisualStyleBackColor = true;
            // 
            // infoTextBox
            // 
            infoTextBox.BackColor = SystemColors.Control;
            infoTextBox.Dock = DockStyle.Fill;
            infoTextBox.Location = new Point(3, 3);
            infoTextBox.Multiline = true;
            infoTextBox.Name = "infoTextBox";
            infoTextBox.ReadOnly = true;
            infoTextBox.Size = new Size(294, 414);
            infoTextBox.TabIndex = 24;
            infoTextBox.TabStop = false;
            // 
            // info2TabPage
            // 
            info2TabPage.Controls.Add(info2TextBox);
            info2TabPage.Location = new Point(4, 24);
            info2TabPage.Name = "info2TabPage";
            info2TabPage.Padding = new Padding(3);
            info2TabPage.Size = new Size(300, 420);
            info2TabPage.TabIndex = 1;
            info2TabPage.Text = "Info 2";
            info2TabPage.UseVisualStyleBackColor = true;
            // 
            // info2TextBox
            // 
            info2TextBox.BackColor = SystemColors.Control;
            info2TextBox.Dock = DockStyle.Fill;
            info2TextBox.Location = new Point(3, 3);
            info2TextBox.Multiline = true;
            info2TextBox.Name = "info2TextBox";
            info2TextBox.ReadOnly = true;
            info2TextBox.Size = new Size(294, 414);
            info2TextBox.TabIndex = 25;
            info2TextBox.TabStop = false;
            // 
            // pictureBox
            // 
            pictureBox.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pictureBox.BackColor = SystemColors.ControlLight;
            pictureBox.Location = new Point(314, 0);
            pictureBox.Name = "pictureBox";
            pictureBox.Size = new Size(644, 447);
            pictureBox.SizeMode = PictureBoxSizeMode.Zoom;
            pictureBox.TabIndex = 1;
            pictureBox.TabStop = false;
            pictureBox.LoadCompleted += pictureBox_LoadCompleted;
            // 
            // fileNameTextBox
            // 
            fileNameTextBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            fileNameTextBox.Location = new Point(12, 179);
            fileNameTextBox.Name = "fileNameTextBox";
            fileNameTextBox.Size = new Size(824, 23);
            fileNameTextBox.TabIndex = 10;
            fileNameTextBox.TabStop = false;
            fileNameTextBox.Visible = false;
            fileNameTextBox.Leave += fileNameTextBox_Leave;
            // 
            // FileEditForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(963, 722);
            Controls.Add(fileNameTextBox);
            Controls.Add(infoPanel);
            Controls.Add(fileInfoButton);
            Controls.Add(label1);
            Controls.Add(notesTextBox);
            Controls.Add(label4);
            Controls.Add(documentIdTextBox);
            Controls.Add(documentIdLabel);
            Controls.Add(processKindGroupBox);
            Controls.Add(fileKindGroupBox);
            Controls.Add(masterFileIdPanel);
            Controls.Add(mainPanel);
            Name = "FileEditForm";
            Text = "FileEditForm";
            Load += FileEditForm_Load;
            Shown += FileEditForm_Shown;
            fileKindGroupBox.ResumeLayout(false);
            fileKindGroupBox.PerformLayout();
            processKindGroupBox.ResumeLayout(false);
            processKindGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)errorProvider).EndInit();
            masterFileIdPanel.ResumeLayout(false);
            masterFileIdPanel.PerformLayout();
            mainPanel.ResumeLayout(false);
            mainPanel.PerformLayout();
            infoPanel.ResumeLayout(false);
            infoTabControl.ResumeLayout(false);
            infoTabPage.ResumeLayout(false);
            infoTabPage.PerformLayout();
            info2TabPage.ResumeLayout(false);
            info2TabPage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private Button browseButton;
        private RadioButton fileKindMasterRadioButton;
        private RadioButton fileKindDerivativeRadioButton;
        private RadioButton fileKindDemoRadioButton;
        private RadioButton processKindKmfRadioButton;
        private RadioButton processKindFundRadioButton;
        private GroupBox fileKindGroupBox;
        private GroupBox processKindGroupBox;
        private OpenFileDialog openFileDialog;
        private Button cancelButton;
        private Button okButton;
        private ErrorProvider errorProvider;
        private TextBox documentIdTextBox;
        private Label documentIdLabel;
        private Label label4;
        private ComboBox masterFileNameComboBox;
        private Label label3;
        private Label label1;
        private TextBox notesTextBox;
        private Panel masterFileIdPanel;
        private Button fileInfoButton;
        private Panel infoPanel;
        private Panel mainPanel;
        private PictureBox pictureBox;
        private TabControl infoTabControl;
        private TabPage infoTabPage;
        private TextBox infoTextBox;
        private TabPage info2TabPage;
        private TextBox info2TextBox;
        private RadioButton processKindEdRadioButton;
        private CheckBox autoGenerateDerivativeCheckBox;
        private ListBox fileNamesListBox;
        private TextBox fileNameTextBox;
        private RadioButton processKindRawRadioButton;
    }
}