using DAA.App.FileUpload.Service;
using DAA.FileUtils;
using DAA.Models.FileUploadApp;
using System.ComponentModel;
using System.Data;

namespace DAA.App.FileUpload
{
    public partial class FileEditForm : Form
    {
        private ImageList _imageList;
        private bool _loading = false;


        private bool _infoPanelVisible;
        private bool InfoPanelVisible
        {
            get { return _infoPanelVisible; }
            set
            {
                _infoPanelVisible = value;

                infoPanel.Visible = _infoPanelVisible;

                if (this.WindowState == FormWindowState.Normal)
                {
                    this.Height = 40 + (_infoPanelVisible ? mainPanel.Height * 2 : mainPanel.Height);
                }

                LoadFileInfo();
            }
        }


        public FileEditForm(ImageList imageList)
        {
            InitializeComponent();
            _imageList = imageList;

            // списъкът вече се взима от номенклатурата в базата
            //openFileDialog.Filter = "All supported files|" + string.Join("", DAA.FileUtils.Consts.SupportedFileExtensions.Values);

            InitComponents();
        }

        private void InitComponents()
        {
            browseButton.ImageList = _imageList;

            browseButton.ImageIndex = 3;
        }

        public async Task InitProcesses()
        {
            processKindEdRadioButton.Visible = Settings.CanQueueEd;
            processKindFundRadioButton.Visible = Settings.CanQueueFund;
            processKindKmfRadioButton.Visible = Settings.CanQueueKmf;
            processKindRawRadioButton.Visible = Settings.CanQueueRaw;

            await SetAllowedExtensions();
        }
        private async Task SetAllowedExtensions()
        {
            string[] extensions = await WebApiClientService.GetAllowedFileExtensions();
            string filter = "All supported files|" + string.Join("", extensions.OrderBy(i => i).Select(i => $"*.{i.ToLower()};"));
            openFileDialog.Filter = filter;
        }

        private bool _fileKindRequired
        {
            get
            {
                return processKindEdRadioButton.Checked || processKindFundRadioButton.Checked;
            }
        }
        private int? _queueItemId;
        private bool _isNew { get => _queueItemId == null; }
        private Guid? _documentId
        {
            get
            {
                return Guid.TryParse(documentIdTextBox.Text, out Guid guid) ? guid : null;
            }
        }
        
        private bool _masterFileIdRequired
        {
            get
            {
                return _fileKindRequired && (fileKindDerivativeRadioButton.Checked || fileKindDemoRadioButton.Checked);
            }
        }
        private bool _autoGenerateDerivativeVisible
        {
            get
            {
                return processKindEdRadioButton.Checked && fileKindMasterRadioButton.Checked;
            }
        }
        public string[] FileNames { get => fileNamesListBox.Items.Cast<string>().ToArray(); }

        private ProcessKind? GetProcessKind()
        {
            return
                processKindEdRadioButton.Checked ? ProcessKind.Ed :
                processKindFundRadioButton.Checked ? ProcessKind.Fund :
                processKindKmfRadioButton.Checked ? ProcessKind.Kmf :
                processKindRawRadioButton.Checked ? ProcessKind.Raw :
                null;
        }

        private FileKind? GetFileKind()
        {
            return
                fileKindMasterRadioButton.Checked ? FileKind.Master :
                fileKindDerivativeRadioButton.Checked ? FileKind.Derivative :
                fileKindDemoRadioButton.Checked ? FileKind.Demo :
                null;
        }
        private string? GetDocumentIdName()
        {
            ProcessKind? processKind = GetProcessKind();
            return
                processKind == ProcessKind.Kmf ? "КМФ Id" :
                processKind == ProcessKind.Raw ? "Опис Id" :
                processKind == ProcessKind.Ed ? "Документ" :
                processKind == ProcessKind.Fund ? "Документ" :
                null;
        }
        private ProcessKind RequireProcessKind()
        {
            return GetProcessKind() ?? throw new Exception("Не е избран вид процес!");
        }

        public async Task NewForMaster(QueueItemModel model)
        {
            await LoadFromModel(model);
            _queueItemId = null;
        }

        public void New()
        {
            _queueItemId = null;
            fileKindMasterRadioButton.Checked = false;
            fileKindDemoRadioButton.Checked = false;
            fileKindDerivativeRadioButton.Checked = false;
            //fileNameTextBox.Clear();
            fileNamesListBox.Items.Clear();

            if (Settings.CanQueueEd && !Settings.CanQueueFund && !Settings.CanQueueKmf && !Settings.CanQueueRaw)
            {
                processKindEdRadioButton.Checked = true;
            }
            if (!Settings.CanQueueEd && Settings.CanQueueFund && !Settings.CanQueueKmf && !Settings.CanQueueRaw)
            {
                processKindFundRadioButton.Checked = true;
            }
            if (!Settings.CanQueueEd && !Settings.CanQueueFund && Settings.CanQueueKmf && !Settings.CanQueueRaw)
            {
                processKindKmfRadioButton.Checked = true;
            }
            if (!Settings.CanQueueEd && !Settings.CanQueueFund && !Settings.CanQueueKmf && Settings.CanQueueRaw)
            {
                processKindRawRadioButton.Checked = true;
            }
        }
        private void FileEditForm_Load(object sender, EventArgs e)
        {
            //ProcessKind_Changed(processKindFundRadioButton, e);
            //FileKind_Changed(fileKindMasterRadioButton, e);
        }

        public async Task LoadFromModel(QueueItemModel model)
        {
            _loading = true;

            _queueItemId = model.Id;

            documentIdTextBox.Text = model.DocumentId.ToString();
            //fileNameTextBox.Text = model.LocalFileName;
            fileNamesListBox.Items.Clear();
            fileNamesListBox.Items.Add(model.LocalFileName);
            //fileNamesListBox.Text = model.LocalFileName;
            autoGenerateDerivativeCheckBox.Checked = model.AutoGenerateDerivative == true;
            notesTextBox.Text = model.Notes;

            if (model.ProcessKind == ProcessKind.Ed)
            {
                processKindEdRadioButton.Checked = true;
            }
            else if (model.ProcessKind == ProcessKind.Fund)
            {
                processKindFundRadioButton.Checked = true;
            }
            else if (model.ProcessKind == ProcessKind.Kmf)
            {
                processKindKmfRadioButton.Checked = true;
            }
            else if (model.ProcessKind == ProcessKind.Raw)
            {
                processKindRawRadioButton.Checked = true;
            }
            else
            {
                processKindEdRadioButton.Checked = false;
                processKindKmfRadioButton.Checked = false;
                processKindFundRadioButton.Checked = false;
                processKindRawRadioButton.Checked = false;
            }

            if (_fileKindRequired)
            {
                if (model.FileKind == FileKind.Master)
                {
                    fileKindMasterRadioButton.Checked = true;
                }
                else if (model.FileKind == FileKind.Derivative)
                {
                    fileKindDerivativeRadioButton.Checked = true;
                }
                else if (model.FileKind == FileKind.Demo)
                {
                    fileKindDemoRadioButton.Checked = true;
                }
                else
                {
                    fileKindMasterRadioButton.Checked = false;
                    fileKindDerivativeRadioButton.Checked = false;
                    fileKindDemoRadioButton.Checked = false;
                }

                if (_masterFileIdRequired)
                {
                    await LoadMasterFilesForDocument();
                    SetMasterDocumentId(model.MasterDocumentId);
                }
            }

            _loading = false;
        }

        public async Task SaveToModel(string fileName, QueueItemModel model)
        {
            model.DocumentId = new Guid(documentIdTextBox.Text);
            model.LocalFileName = fileName; //fileNameTextBox.Text;

            model.Checksum = await ChecksumUtil.Calculate(model.LocalFileName);
            model.ProcessKind = RequireProcessKind();
            model.FileKind = _fileKindRequired ? (GetFileKind() ?? throw new Exception("Не е избран вид файл!")) : null;
            model.Size = new FileInfo(model.LocalFileName).Length;
            model.MasterDocumentId = _masterFileIdRequired ? GetMasterDocumentId() : null;
            model.AutoGenerateDerivative = _autoGenerateDerivativeVisible && autoGenerateDerivativeCheckBox.Checked;
            model.Notes = !string.IsNullOrWhiteSpace(notesTextBox.Text) ? notesTextBox.Text : null;

        }

        private void BrowseButton_Click(object sender, EventArgs e)
        {
            openFileDialog.Multiselect = _isNew;

            if (openFileDialog.ShowDialog() == DialogResult.OK)
            {
                fileNamesListBox.Items.Clear();
                fileNamesListBox.Items.AddRange(openFileDialog.FileNames);
                if (fileNamesListBox.Items.Count > 0)
                {
                    fileNamesListBox.SelectedIndex = 0;
                }
                LoadFileInfo();
            }
        }

        private async Task<bool> CustomValidate()
        {
            bool result = true;
            //errorProvider.SetError(fileNameTextBox, string.Empty);
            errorProvider.SetError(fileNamesListBox, string.Empty);
            errorProvider.SetError(processKindGroupBox, string.Empty);
            errorProvider.SetError(fileKindGroupBox, string.Empty);
            errorProvider.SetError(documentIdTextBox, string.Empty);
            errorProvider.SetError(masterFileIdPanel, string.Empty);
            errorProvider.SetError(browseButton, string.Empty);


            if (string.IsNullOrWhiteSpace(documentIdTextBox.Text))
            {
                result = false;
                errorProvider.SetError(documentIdTextBox, $"Въведете идентификатор на {GetDocumentIdName()}.");
            }
            else
            {
                try
                {
                    await CheckDocumentId();
                }
                catch (Exception e)
                {
                    result = false;
                    errorProvider.SetError(documentIdTextBox, e.Message);
                }
            }

            if (fileNamesListBox.Items.Count == 0)
            {
                result = false;
                errorProvider.SetError(browseButton, "Изберете файл за качване!");
            }
            else
            {
                string errors = "";

                foreach (string fileName in FileNames)
                {
                    try
                    {
                        await CheckFileName(fileName);
                    }
                    catch (Exception e)
                    {
                        errors += $"{Environment.NewLine}{fileName}: {e.Message}";
                        fileNamesListBox.Items.Remove(fileName);
                    }
                }

                if (!string.IsNullOrEmpty(errors))
                {
                    result = false;
                    errors = "Грешки в следните файлове - премахнати са от списъка:" + errors;
                    errorProvider.SetError(browseButton, errors);
                }
            }

            //if (string.IsNullOrWhiteSpace(fileNameTextBox.Text))
            //{
            //    result = false;
            //    errorProvider.SetError(browseButton, "Изберете файл за качване!");
            //}
            //else if (!File.Exists(fileNameTextBox.Text))
            //{
            //    result = false;
            //    errorProvider.SetError(browseButton, $"Не е намерен файл с име {fileNameTextBox.Text}!");
            //}
            //else
            //{
            //    try
            //    {
            //        await CheckFileName();
            //    }
            //    catch (Exception e)
            //    {
            //        result = false;
            //        errorProvider.SetError(browseButton, e.Message);
            //    }
            //}



            if (!processKindFundRadioButton.Checked && !processKindEdRadioButton.Checked && !processKindKmfRadioButton.Checked && !processKindRawRadioButton.Checked)
            {
                result = false;
                errorProvider.SetError(processKindGroupBox, "Изберете процес - ЕД, КМФ, Фонд, Опис!");
            }

            if (_fileKindRequired && !fileKindMasterRadioButton.Checked && !fileKindDerivativeRadioButton.Checked && !fileKindDemoRadioButton.Checked)
            {
                result = false;
                errorProvider.SetError(fileKindGroupBox, "Изберете вид файл - основен, производен, демо!");
            }

            if (_masterFileIdRequired && masterFileNameComboBox.SelectedIndex < 0)
            {
                result = false;
                errorProvider.SetError(masterFileIdPanel, "Изберете master файл, към който се прикача производен/демо!");
            }

            return result;
        }

        private async Task ValidateFile(string fileName)
        {
            if (Settings.AppSettings.ScanWithAntivirusClientApp)
            {
                try
                {
                    AntivirusUtil.Scan(fileName);
                }
                catch (Exception e)
                {
                    MessageBox.Show($"{e.GetType()}: {e.Message}");
                }
            }
            await ValidateUtil.ValidateFile(fileName, Settings.AppSettings);
        }

        private string GetValidationErrors()
        {
            List<string> errors = new();
            GetValidationErrorsHelp(this, errors);
            return string.Join(Environment.NewLine, errors);
        }

        private void GetValidationErrorsHelp(Control control, List<string> errors)
        {
            string error = errorProvider.GetError(control);
            if (!string.IsNullOrWhiteSpace(error))
            {
                errors.Add(error);
            }

            if (control.HasChildren)
            {
                foreach (Control child in control.Controls)
                {
                    GetValidationErrorsHelp(child, errors);
                }
            }
        }

        private async void okButton_Click(object sender, EventArgs e)
        {
            if (!await CustomValidate())
            {
                throw new Exception($"Грешки във въведените данни {Environment.NewLine}{GetValidationErrors()}");
                //return;
            }
            else
            {
                foreach (string fileName in FileNames)
                {
                    await ValidateFile(fileName);
                }

                DialogResult = DialogResult.OK;
            }

        }

        private void ProcessKind_Changed(object sender, EventArgs e)
        {
            fileKindGroupBox.Visible = _fileKindRequired;
            masterFileIdPanel.Visible = _masterFileIdRequired;
            autoGenerateDerivativeCheckBox.Visible = _autoGenerateDerivativeVisible;
            documentIdLabel.Text = GetDocumentIdName();
        }

        private async void FileKind_Changed(object sender, EventArgs e)
        {
            masterFileIdPanel.Visible = _masterFileIdRequired;
            autoGenerateDerivativeCheckBox.Visible = _autoGenerateDerivativeVisible;
            // получаваше се едновременно извикване на LoadMasterFilesForDocument оттук и от LoadFromModel -
            // избраният елемент от падащото меню не се зареждаше правилно - оставаше на първия в списъка
            if (!_loading)
            {
                await LoadMasterFilesForDocument();
            }
        }

        private async void documentIdTextBox_Leave(object sender, EventArgs e)
        {
            masterFileNameComboBox.DataSource = null;
            if (documentIdTextBox.Text != "")
            {
                await CheckDocumentId();
                await LoadMasterFilesForDocument();
            }

        }
        private async void fileNameTextBox_Leave(object sender, EventArgs e)
        {
            //if (fileNameTextBox.Text != "")
            //{
            //    await CheckFileName();
            //    string extension = Path.GetExtension(fileNameTextBox.Text);

            //    fileInfoButton.Visible = true; //Consts.IsImageExtension(extension);
            //}
        }
        private async Task CheckDocumentId()
        {
            Guid? documentId = _documentId;
            if (documentId.HasValue)
            {
                ProcessKind processKind = RequireProcessKind();
                if (!await WebApiClientService.DocumentExists(processKind, documentId))
                {
                    throw new Exception($"В системата липсва {GetDocumentIdName()?.ToLower()} за {processKind}-{documentId}");
                }
            }
            else
            {
                throw new Exception($"Въведеният идентификатор на {GetDocumentIdName()} е невалиден!");
            }
        }

        private async Task CheckFileName(string fileName)
        {
            //string fileName = Path.GetFileName(fileNameTextBox.Text);
            if (await WebApiClientService.FileExists(GetProcessKind(), GetFileKind(), _documentId, _queueItemId, fileName))
            {
                throw new Exception($"В системата вече има качен или чакащ в опашката файл {GetProcessKind()}:{GetFileKind()}:{_documentId}:{_queueItemId}{Environment.NewLine}{fileName}");
            }
        }

        private async Task LoadMasterFilesForDocument()
        {
            //Console.WriteLine("LoadMasterFilesForDocument - begin");

            Guid? lastSelected = masterFileNameComboBox.SelectedItem != null ?
                ((CodeNameModel)masterFileNameComboBox.SelectedItem).Code : null;

            masterFileNameComboBox.DataSource = null;
            ProcessKind? processKind = GetProcessKind();
            if ((processKind == ProcessKind.Fund || processKind == ProcessKind.Ed) && _documentId != null)
            {
                CodeNameModel[] masterFiles = await WebApiClientService.MastersForDocument(_documentId);
                //masterFileNameComboBox.Items.AddRange(masterFiles);
                masterFileNameComboBox.DataSource = masterFiles;
                masterFileNameComboBox.ValueMember = nameof(CodeNameModel.Code);
                masterFileNameComboBox.DisplayMember = nameof(CodeNameModel.Name);

                CodeNameModel? item = masterFiles.Where(x => x.Code == lastSelected).FirstOrDefault();
                if (item != null)
                {
                    masterFileNameComboBox.SelectedItem = item;
                }
            }

            //Console.WriteLine("LoadMasterFilesForDocument - end");
        }

        private Guid? GetMasterDocumentId()
        {
            return masterFileNameComboBox.SelectedItem != null ? ((CodeNameModel)masterFileNameComboBox.SelectedItem).Code : null;
        }
        private void SetMasterDocumentId(Guid? documentId)
        {
            //Console.WriteLine($"SetMasterDocumentId - start, {masterFileNameComboBox.SelectedValue}, {documentId}");
            masterFileNameComboBox.SelectedValue = documentId;
            //Console.WriteLine($"SetMasterDocumentId - end, {masterFileNameComboBox.SelectedValue}, {documentId}");
        }

        private void documentIdTextBox_Enter(object sender, EventArgs e)
        {
            ((TextBox)sender).SelectAll();
        }

        private void fileInfoButton_Click(object sender, EventArgs e)
        {
            InfoPanelVisible = !InfoPanelVisible;
        }

        private void FileEditForm_Shown(object sender, EventArgs e)
        {
            InfoPanelVisible = false;
            processKindGroupBox.Focus();
        }

        private void LoadFileInfo()
        {
            if (InfoPanelVisible)
            {
                infoTextBox.Text = null;
                info2TextBox.Text = null;

                //string fileName = fileNameTextBox.Text;
                string fileName = (string)fileNamesListBox.SelectedItem;
                if (File.Exists(fileName))
                {
                    if (DAA.FileUtils.Consts.IsImageExtension(Path.GetExtension(fileName)))
                    {
                        pictureBox.ImageLocation = fileName;
                        pictureBox.LoadAsync();
                    }
                    else
                    {
                        pictureBox.Image = null;
                    }

                    info2TextBox.Text = MetadataUtil.GetFileMetadata(fileName);
                    if (pictureBox.Image == null && !string.IsNullOrEmpty(info2TextBox.Text))
                    {
                        infoTabControl.SelectedTab = info2TabPage;
                    }
                }
            }
            else
            {
                pictureBox.Image = null;
            }
        }

        private void pictureBox_LoadCompleted(object sender, AsyncCompletedEventArgs e)
        {
            infoTextBox.Text = MetadataUtil.GetImageDescription(pictureBox.Image);
        }

        private void fileNamesListBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            LoadFileInfo();
        }
    }
}
