using DAA.Data;
using DAA.Extensions.DynamicLinq;
using DAA.Models.DigitalObjects;
using DAA.Models.Reports;
using DAA.Shared;
using MVsFileTypes.Predefined.FileTypes;
using Task = System.Threading.Tasks.Task;

namespace DAA.Services.DigitalObjects
{
    public interface IDigitalObjectServiceBase
    {
        protected internal Task<Guid> CreateDraftInternalAsync(DigitalObjectDraftModel model, bool fileExists = false, bool autogenerateDerivative = false);
        protected internal Task<Guid> CreateDraftFromPackageDocumentInternalAsync(PackageDocument doc, DigitalObjectDraftModel model, bool autogenerateDerivative = false);
        protected internal Task<Guid> CreateDigitalObjectInternalAsync(DigitalObjectModel model, Guid? createdBy = null, DateTime? createdOn = null);
        protected internal Task<Guid> CreateOrUpdateDigitalObjectFromDraftInternalAsync(
            Guid sysId, 
            bool updateFileContent, 
            bool overwriteCreatedFromDraft = true, 
            bool overwriteModifiedFromDraft = true);
        protected internal Task<Guid> UpdateDraftInternalAsync(DigitalObjectDraftModel model, bool updateFile);
        protected internal Task<Guid> UpdateDigitalObjectInternalAsync(DigitalObjectModel model, Guid? updatedBy = null, DateTime? updatedOn = null);
        protected internal Task DeleteDraftInternalAsync(int id, bool includeRelated = false, bool includeFiles = false);
        protected internal Task DeleteDigitalObjectInternalAsync(Guid sysId, bool includeRelated = false, bool includeFiles = false);
    }

    public interface IDigitalObjectService : IDigitalObjectServiceBase
    {
        Task<DataSourceResponseModel<DigitalObjectDisplayModel?>> GetByDocumentIdentifierAsync(
            DataSourceRequestModel model,
            Guid? documentSysId,
            bool documentHasExternalSource = false,
            int? documentExternalIdentifier = null,
            bool? digitized = null,
            bool includeDeleted = false);
        Task<DataSourceResponseModel<DigitalObjectDisplayModel?>> GetByInventoryIdentifierAsync(
            DataSourceRequestModel model,
            Guid? inventorySysId,
            bool inventoryHasExternalSource = false,
            int? inventoryExternalIdentifier = null,
            bool includeDeleted = false);
        Task<DigitalObjectDisplayModel?> GetDigitalObjectByDocumentIdentifierAsync(
            string digitalObjectName,
            Guid documentSysId);
        Task<OperationResult> ManageDigitalObjectReviewAsync(DigitalObjectDisplayModel digitalObject);
        Task<DigitalObjectDisplayModel?> GetDigitalObjectBySystemIdentifierAsync(Guid sysId);
        Task<DigitalObjectDisplayModel?> GetCurrentDraftAsync(Guid sysId);
        Task<bool> HasCurrentDraftAsync(Guid sysId);
        Task<bool> IsCurrentDraftAsync(DigitalObjectDraftModel model);
        Task<bool> IsReadOnlyDraftAsync(DigitalObjectDraftModel model);
        Task<OperationResult> CreateDraftAsync(DigitalObjectDraftModel model, bool autogenerateDerivative = false);
        Task<OperationResult> CreateDigitalObjectAsync(DigitalObjectModel model);
        Task<OperationResult> CreateOrUpdateDigitalObjectFromDraftAsync(Guid sysId, bool updateFileContent = false);

        Task<OperationResult> UpdateDraftAsync(DigitalObjectDraftModel model);
        Task<OperationResult> UpdateDigitalObjectAsync(DigitalObjectModel model);
        Task<OperationResult> DeleteDraftAsync(int id, bool includeRelated = false, bool includeFiles = false);
        Task<OperationResult> DeleteDigitalObjectAsync(Guid sysId, bool includeRelated = false, bool includeFiles = false);
        Task<DigitalObjectDisplayModel?> GetFromExternalSourceAsync(
            int externalIdentifier,
            Guid? systemIdentifier = null,
            Guid? documentSystemIdentifier = null,
            Guid? archivalEntitySystemIdentifier = null,
            Guid? inventorySystemIdentifier = null,
            Guid? fundSystemIdentifier = null);
        ReportGridResponseModel<DigitalObjectReviewDisplayModel> GetDigitalObjectReviewsAsync(ReportGridRequestModel<DigitalObjectReviewSearchModel> model);
        Task<byte[]> ConvertTiffToImage(byte[] content);
        Task<DigitalObjectPublicDisplayModel?> GetDigitalObjectDraftBySystemIdentifierAsync(Guid sysId);
    }
}
